function A_d = A_d_num_slip(in1,in2,in3)
%A_d_num_slip
%    A_d = A_d_num_slip(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    10-Apr-2023 22:21:23

L = in3(:,1);
delta_t = in3(:,2);
u_lin1 = in2(1,:);
x_lin3 = in1(3,:);
x_lin4 = in1(4,:);
A_d = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-delta_t.*u_lin1.*sin(x_lin3),delta_t.*u_lin1.*cos(x_lin3),1.0,0.0,0.0,0.0,(delta_t.*u_lin1.*(tan(x_lin4).^2+1.0))./L,1.0],[4,4]);
