function B_d = B_d_num_slip(in1,in2,in3)
%B_d_num_slip
%    B_d = B_d_num_slip(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    10-Apr-2023 22:21:23

L = in3(:,1);
delta_t = in3(:,2);
x_lin3 = in1(3,:);
x_lin4 = in1(4,:);
B_d = reshape([delta_t.*cos(x_lin3),delta_t.*sin(x_lin3),(delta_t.*tan(x_lin4))./L,0.0,0.0,0.0,0.0,delta_t],[4,2]);
