function f_d = f_d_num(in1,in2,in3)
%F_D_NUM
%    F_D = F_D_NUM(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    10-Apr-2023 22:13:12

L = in3(:,1);
delta_t = in3(:,2);
u_k1 = in2(1,:);
u_k2 = in2(2,:);
x_k1 = in1(1,:);
x_k2 = in1(2,:);
x_k3 = in1(3,:);
x_k4 = in1(4,:);
f_d = [x_k1+delta_t.*u_k1.*cos(x_k3);x_k2+delta_t.*u_k1.*sin(x_k3);x_k3+(delta_t.*u_k1.*tan(x_k4))./L;x_k4+delta_t.*u_k2];
