function f = f_num_slip(in1,in2,in3)
%F_NUM_SLIP
%    F = F_NUM_SLIP(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    10-Apr-2023 22:21:23

L = in3(:,1);
u1 = in2(1,:);
u2 = in2(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
f = [u1.*cos(x3);u1.*sin(x3);(u1.*tan(x4))./L;u2];
